[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow_doerz = "w6XLMEHf4xg9VYQERCWkgnA5YDSuZYJo1Ub71sajwZu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
